import { createSecondaryEhc } from "@/pages/secondary-ehc/helpers/createSecondaryEhc";

export const endpoints = {
  login: "api/login",
  signup: "api/firm/register",
  signupMeta: "api/form-data",
  forgotpassword: "api/forgot-password",
  resetpassword: "/api/reset-password",
  dashboard: "api/v2/dashboard",
  workstation_list: "api/v2/file/workstation",
  matterMeta: "api/v2/file/initial/meta",
  createMatter: "api/v2/file/initial/save",
  matter: "api/v2/file/initial/show",
  applicantMeta: "api/v2/file/applicant-information/meta",
  createApplicantInfo: "api/v2/file/applicant-information",
  applicantInfo: "api/v2/file/applicant-information/show",
  createIdentification: "api/v2/file/identification",
  identificationMeta: "api/v2/file/identification/meta",
  identification: "api/v2/file/identification/show",
  createEmployment: "api/v2/file/employement",
  employmentMeta: "api/v2/file/employement/meta",
  employment: "api/v2/file/employement/show",
  schoolCaregiver: "api/v2/file/school-or-caregiver/show",
  createSchoolCaregiver: "api/v2/file/school-or-caregiver",
  schoolCaregiverMeta: "api/v2/file/school-or-caregiver/meta",
  representativeReferral: "api/v2/file/representative-referral/show",
  createRepresentativeReferral: "api/v2/file/representative-referral",
  representativeReferralMeta: "api/v2/file/representative-referral/meta",
  createPrimaryEhc: "api/v2/file/primary-ehc",
  primaryEhcmeta: "api/v2/file/primary-ehc/meta",
  primaryEhc: "api/v2/file/primary-ehc/show",
  createSecondaryEhc: "api/v2/file/secondary-ehc",
  secondaryEhcMeta: "api/v2/file/secondary-ehc/meta",
  secondaryEhc: "api/v2/file/secondary-ehc/show",
};
