import { add } from "date-fns";
import { de, th } from "date-fns/locale";

export const endpoints = {
  login: "api/login",
  signup: "api/firm/register",
  signupMeta: "api/form-data",
  forgotpassword: "api/forgot-password",
  resetpassword: "/api/reset-password",
  dashboard: "api/v2/dashboard",
  uploadAttachment: "api/v2/attachment",
  workstation_list: "api/v2/file/workstation",
  matterMeta: "api/v2/file/initial/meta",
  createMatter: "api/v2/file/initial/save",
  matter: "api/v2/file/initial/show",
  applicantMeta: "api/v2/file/applicant-information/meta",
  createApplicantInfo: "api/v2/file/applicant-information",
  applicantInfo: "api/v2/file/applicant-information/show",
  createIdentification: "api/v2/file/identification",
  identificationMeta: "api/v2/file/identification/meta",
  identification: "api/v2/file/identification/show",
  createEmployment: "api/v2/file/employement",
  employmentMeta: "api/v2/file/employement/meta",
  employment: "api/v2/file/employement/show",
  schoolCaregiver: "api/v2/file/school-or-caregiver/show",
  createSchoolCaregiver: "api/v2/file/school-or-caregiver",
  schoolCaregiverMeta: "api/v2/file/school-or-caregiver/meta",
  representativeReferral: "api/v2/file/representative-referral/show",
  createRepresentativeReferral: "api/v2/file/representative-referral",
  representativeReferralMeta: "api/v2/file/representative-referral/meta",
  createPrimaryEhc: "api/v2/file/primary-ehc",
  primaryEhcmeta: "api/v2/file/primary-ehc/meta",
  primaryEhc: "api/v2/file/primary-ehc/show",
  createSecondaryEhc: "api/v2/file/secondary-ehc",
  secondaryEhcMeta: "api/v2/file/secondary-ehc/meta",
  secondaryEhc: "api/v2/file/secondary-ehc/show",
  createAccidentInfo: "api/v2/file/accident-detail",
  accidentInfoMeta: "api/v2/file/accident-detail/meta",
  accidentInfo: "api/v2/file/accident-detail/show",
  createInsurance: "api/v2/file/accident-benefits/insurance",
  insurance: "api/v2/file/accident-benefits/insurance/show",
  metaAccidentBenefits: "api/v2/file/accident-benefits/meta",
  adjuster: "api/v2/file/accident-benefits/adjuster/show",
  createAdjuster: "api/v2/file/accident-benefits/adjuster",
  deleteAdjuster: "api/v2/file/accident-benefits/adjuster/delete",
  vechile: "api/v2/file/accident-benefits/vehicle/show",
  createVechile: "api/v2/file/accident-benefits/vehicle",
  deleteVechile: "api/v2/file/accident-benefits/adjuster/delete",
  sectionList: "api/v2/file/accident-benefits/section-33/list",
  section: "api/v2/file/accident-benefits/section-33/show",
  createSection: "api/v2/file/accident-benefits/section-33",
  updateSection: "api/v2/file/accident-benefits/section-33",
  deleteSectionList: "api/v2/file/accident-benefits/section-33/delete",
  deleteSectionCommunication:
    "api/v2/file/accident-benefits/section-33/delete-communication",
  deleteSectiondocument:
    "api/v2/file/accident-benefits/section-33/delete-document",
  latList: "api/v2/file/accident-benefits/lat/list",
  deleteLat: "api/v2/file/accident-benefits/lat",
  lat: "api/v2/file/accident-benefits/lat/show",
  createLat: "api/v2/file/accident-benefits/lat",
  updateLat: "api/v2/file/accident-benefits/lat",
  createAbCounsel: "api/v2/file/accident-benefits/ab-counsel",
  abCounsel: "api/v2/file/accident-benefits/ab-counsel/show",
  createTpInsurance: "api/v2/file/third-party/insurance",
  tpInsurance: "api/v2/file/third-party/insurance/show",
  deleteTpInsurance: "api/v2/file/third-party/insurance/delete",
  createTpAdjuster: "api/v2/file/third-party/adjuster",
  tpAdjuster: "api/v2/file/third-party/adjuster/show",
  deleteTpAdjuster: "api/v2/file/third-party/adjuster/delete",
  driverInfo: "api/v2/file/third-party/driver-information/show",
  createDriverInfo: "api/v2/file/third-party/driver-information",
  createOwnerInfo: "api/v2/file/third-party/owner-information",
  ownerInfo: "api/v2/file/third-party/owner-information/show",
  deleteOwnerInfo: "api/v2/file/third-party/owner-information/delete",
  deleteOwnerDirector:
    "api/v2/file/third-party/owner-information/director-delete",
  createTpVechile: "api/v2/file/third-party/vehicle",
  tpVechile: "api/v2/file/third-party/vehicle/show",
  section258List: "api/v2/file/third-party/section-258/list",
  createSection258: "api/v2/file/third-party/section-258",
  section258: "api/v2/file/third-party/section-258/show",
  updateSection258: "api/v2/file/third-party/section-258",
  deleteSection258Communication:
    "api/v2/file/third-party/section-258/delete-communication",
  deleteSection258document:
    "api/v2/file/third-party/section-258/delete-document",
  deleteSection258List: "api/v2/file/third-party/section-258/delete",
  createTpCounsel: "api/v2/file/third-party/tp-counsel",
  tpCounsel: "api/v2/file/third-party/tp-counsel/show",
  soc: "api/v2/file/soc/show",
  createSoc: "api/v2/file/soc",
  createStatement: "api/v2/file/soc/statamnet-of-defence",
  statement: "api/v2/file/soc/statamnet-of-defence/show",
  createScheduled: "api/v2/file/discovery/scheduled",
  scheduled: "api/v2/file/discovery/scheduled/show",
  createAod: "api/v2/file/discovery/aod",
  aod: "api/v2/file/discovery/aod/show",
  createUndertaking: "api/v2/file/discovery/undertaking",
  undertaking: "api/v2/file/discovery/undertaking/show",
  conflictList: "api/v2/file/document/list/conflict-search",
  createConflict: "api/v2/file/document/save/conflict-search",
  deleteConflict: "api/v2/file/document/delete",
  updateConflict: "api/v2/file/document",
  createClient: "api/v2/file/document/save/client-documents",
  clientList: "api/v2/file/document/list/client-documents",
  updateClient: "api/v2/file/document",
  deleteClient: "api/v2/file/document/delete",
  createInsuranceDoc: "api/v2/file/document/save/insurance-ownership",
  insuranceDocList: "api/v2/file/document/list/insurance-ownership",
  deleteInsuranceDoc: "api/v2/file/document/delete",
  updateInsuranceDoc: "api/v2/file/document",
  createPolice: "api/v2/file/document/save/police-report",
  updatePolice: "api/v2/file/document",
  policeList: "api/v2/file/document/list/police-report",
  deletePolice: "api/v2/file/document/delete",
  createMedical: "api/v2/file/document/save/medical-reports",
  updateMedical: "api/v2/file/document",
  medicalList: "api/v2/file/document/list/medical-reports",
  deleteMedical: "api/v2/file/document/delete",
  createAccounting: "api/v2/file/document/save/accounting",
  updateAccounting: "api/v2/file/document",
  accountinglist: "api/v2/file/document/list/accounting",
  deleteAccounting: "api/v2/file/document/delete",
  createClientCorrespondence: "api/v2/file/correspondence/save/client",
  clientCorrespondenceList: "api/v2/file/correspondence/list/client",
  updateClientCorrespondence: "api/v2/file/correspondence",
  deleteClientCorrespondence: "api/v2/file/correspondence/delete",
  createInsuranceExamination: "api/v2/file/insurance-examination",
  updateInsuranceExamnation: "api/v2/file/insurance-examination",
  insuranceExamination: "api/v2/file/insurance-examination/show",
  deleteInsuranceExamination: "api/v2/file/insurance-examination/delete",
  insuranceExaminationList: "api/v2/file/insurance-examination/list",
  createVsrInsuranceExamination: "api/v2/file/vsr-examination",
  updateVsrInsuranceExamnation: "api/v2/file/vsr-examination",
  vsrInsuranceExamination: "api/v2/file/vsr-examination/show",
  deleteVsrInsuranceExamination: "api/v2/file/vsr-examination/delete",
  vsrInsuranceExaminationList: "api/v2/file/vsr-examination/list",
  createOcf: "api/v2/file/tracking/production/ocf-productions",
  ocf: "api/v2/file/tracking/production/ocf-productions/show",
  createOcf1: "api/v2/file/tracking/production/ocf-1",
  ocf1: "api/v2/file/tracking/production/ocf-1/show",
  createOcf2: "api/v2/file/tracking/production/ocf-2",
  ocf2: "api/v2/file/tracking/production/ocf-2/show",
  createOcf3: "api/v2/file/tracking/production/ocf-3",
  ocf3: "api/v2/file/tracking/production/ocf-3/show",
  createOcf5: "api/v2/file/tracking/production/ocf-5",
  ocf5: "api/v2/file/tracking/production/ocf-5/show",
  createOcf6: "api/v2/file/tracking/production/ocf-6",
  ocf6: "api/v2/file/tracking/production/ocf-6/show",
  createOcf10: "api/v2/file/tracking/production/ocf-10",
  ocf10: "api/v2/file/tracking/production/ocf-10/show",
  createOhif: "api/v2/file/tracking/production/ohip-decorded-summary",
  ohif: "api/v2/file/tracking/production/ohip-decorded-summary/show",
  deleteOhif: "api/v2/file/tracking/production/ohip-decorded-summary/delete",
  createPoliceReport: "api/v2/file/tracking/production/police-report",
  policeReport: "api/v2/file/tracking/production/police-report/show",
  deletePoliceReport: "api/v2/file/tracking/production/police-report/delete",
  createHospitalReport: "api/v2/file/tracking/production/hospital-report",
  hospitalReport: "api/v2/file/tracking/production/hospital-report/show",
  deleteHospitalReport:
    "api/v2/file/tracking/production/hospital-report/delete",
  createAmbulanceReport: "api/v2/file/tracking/production/ambulance-report",
  ambulanceReport: "api/v2/file/tracking/production/ambulance-report/show",
  deleteAmbulanceReport:
    "api/v2/file/tracking/production/ambulance-report/delete",
  createFamilyDoctor: "api/v2/file/tracking/production/family-doctor-cnr",
  familyDoctor: "api/v2/file/tracking/production/family-doctor-cnr/show",
  deleteFamilyDoctor:
    "api/v2/file/tracking/production/family-doctor-cnr/delete",
  createPharmacy:
    "api/v2/file/tracking/production/pharmacy-prescription-summary",
  pharmacy:
    "api/v2/file/tracking/production/pharmacy-prescription-summary/show",
  deletePharmacy:
    "api/v2/file/tracking/production/pharmacy-prescription-summary/delete",
  createPhysiotherapy: "api/v2/file/tracking/production/physiotherapy-cnr",
  physiotherapy: "api/v2/file/tracking/production/physiotherapy-cnr/show",
  deletePhysiotherapy:
    "api/v2/file/tracking/production/physiotherapy-cnr/delete",
  createWalk: "api/v2/file/tracking/production/walk-in-clinic-cnr",
  walk: "api/v2/file/tracking/production/walk-in-clinic-cnr/show",
  deleteWalk: "api/v2/file/tracking/production/walk-in-clinic-cnr/delete",
  createStatutory: "api/v2/file/tracking/statutory-declaration",
  statutory: "api/v2/file/tracking/statutory-declaration/show",
  createTax: "api/v2/file/tracking/tax-returns",
  tax: "api/v2/file/tracking/tax-returns/show",
  createBank: "api/v2/file/tracking/bank-statements",
  bank: "/api/v2/file/tracking/bank-statements/show",
  createSue: "api/v2/file/tracking/sue-to-driver-owner",
  sue: "api/v2/file/tracking/sue-to-driver-owner/show",
  deleteSue: "api/v2/file/tracking/sue-to-driver-owner/delete",
  createNonEngagement: "api/v2/file/tracking/non-engagement",
  deleteNonEngagement: "api/v2/file/tracking/sue-to-driver-owner/delete",
  nonEngagement: "api/v2/file/tracking/non-engagement/show",
  CreateClientSettlement: "api/v2/file/client-memo-settlement",
  clientSettlement: "api/v2/file/client-memo-settlement/show",
  createCost: "api/v2/file/accounting/expence",
  createTask: "api/v2/task/store",
  updateTask: "api/v2/task",
  taskList: "api/v2/task/list",
  deleteTask: "api/v2/task/delete",
  taskMeta: "api/v2/task/meta",
  task: "api/v2/task/show",
  updateStatus: "api/v2/task/update-status",
  searchContact: "api/v2/task/search",
  deleteReminder: "api/v2/task/deleteReminder",
  deleteAttachment: "api/v2/task/deleteAttachment",
  postComment: "api/v2/task/comment",
  comment: "api/v2/task/comment/list",
  // Calendar/Event endpoints
  eventMeta: "api/v2/event/meta",
  eventList: "api/v2/event/list",
  eventShow: "api/v2/event/show",
  createEvent: "api/v2/event/store",
  updateEvent: "api/v2/event/update",
  deleteEvent: "api/v2/event/delete",
  filterTasks: "api/v2/task/filter",
  ocfProdList: "api/v2/file/production/ocf-1/list",
  createOcfProd: "api/v2/file/production/ocf-1",
  updateOcfProd: "api/v2/file/production/ocf-1",
  ocfProd: "api/v2/file/production/ocf-1/show",
  deleteOcfProdList: "api/v2/file/production/ocf-1/delete",
  ocfProdPrint: "api/v2/file/production/ocf-1/print",
  ocfProd2List: "api/v2/file/production/ocf-2/list",
  createOcfProd2: "api/v2/file/production/ocf-2",
  updateOcfProd2: "api/v2/file/production/ocf-2",
  ocfProdtwo: "api/v2/file/production/ocf-2/show",
  deleteOcfProd2List: "api/v2/file/production/ocf-2/delete",
  ocfProdPrint2: "api/v2/file/production/ocf-2/print",
  ocfProd5List: "api/v2/file/production/ocf-5/list",
  createOcfProd5: "api/v2/file/production/ocf-5",
  updateOcfProd5: "api/v2/file/production/ocf-5",
  ocfProd5: "api/v2/file/production/ocf-5/show",
  deleteOcfProd5List: "api/v2/file/production/ocf-5/delete",
  ocfProdPrint5: "api/v2/file/production/ocf-5/print",
  ocfProd6List: "api/v2/file/production/ocf-6/list",
  createOcfProd6: "api/v2/file/production/ocf-6",
  updateOcfProd6: "api/v2/file/production/ocf-6",
  ocfProd6: "api/v2/file/production/ocf-6/show",
  deleteOcfProd6List: "api/v2/file/production/ocf-6/delete",
  ocfProdPrint6: "api/v2/file/production/ocf-6/print",
  ocfProd10List: "api/v2/file/production/ocf-10/list",
  createOcfProd10: "api/v2/file/production/ocf-10",
  updateOcfProd10: "api/v2/file/production/ocf-10",
  ocfProd10: "api/v2/file/production/ocf-10/show",
  deleteOcfProd10List: "api/v2/file/production/ocf-10/delete",
  ocfProdPrint10: "api/v2/file/production/ocf-10/print",
  socProdList: "api/v2/file/production/soc-draft/list",
  createSocProd: "api/v2/file/production/soc-draft",
  updateSocProd: "api/v2/file/production/soc-draft",
  socProd: "api/v2/file/production/soc-draft/show",
  deleteSocProdList: "api/v2/file/production/soc-draft/delete",
  socProdPrint: "api/v2/file/production/soc-draft/print",
  mvaProdList: "api/v2/file/production/mva-client-fillable/list",
  createMvaProd: "api/v2/file/production/mva-client-fillable",
  updateMvaProd: "api/v2/file/production/mva-client-fillable",
  mvaProd: "api/v2/file/production/mva-client-fillable/show",
  deleteMvaProdList: "api/v2/file/production/mva-client-fillable/delete",
  mvaProdPrint: "api/v2/file/production/mva-client-fillable/print",
  psychologicalList: "api/v2/file/production/psychological/list",
  createPsychological: "api/v2/file/production/psychological",
  updatePsychological: "api/v2/file/production/psychological",
  psychological: "api/v2/file/production/psychological/show",
  deletePsychologicalList: "api/v2/file/production/psychological/delete",
  psychologicalPrint: "api/v2/file/production/psychological/print",
  inbox: "api/v2/email/folder/inbox",
  sent: "api/v2/email/folder/sent",
  email: "api/v2/email",
  draft: "api/v2/email/folder/draft",
  saveDraft: "api/v2/email/draft",
  createEmail: "api/v2/email/send",
  exportApplicantMeta: "api/v2/export/applicant-information",
  exportApplicantInfo: "api/v2/export/export-applicant-information",
  fileAssignedInfoMeta: "api/v2/export/file-assigned-info",
  fileAssignedInfo: "api/v2/export/export-file-assigned-info",
  listOfFile: "api/v2/export/export-list-of-files",
  applicantContactInfo: "api/v2/export/export-applicant-contact-information",
  applicantAccidentDetail: "api/v2/export/export-applicant-accident-detail",
  mvaCasesByMedicalCentreMeta: "api/v2/export/mva-cases-by-medical-centre",
  vehicleOwnershipInfo: "api/v2/export/export-vehicle-ownership-information",
  vehicleOwnershipMeta: "api/v2/export/vehicle-ownership-information",
  mvaCasesExport: "api/v2/export/export-mva-cases-by-medical-centre",
  latFilesExport: "api/v2/export/export-lat-files",
  s33RequestExport: "api/v2/export/export-s33-request",
  s258RequestExport: "api/v2/export/export-s258-request",
  opposingCounselExport: "api/v2/export/export-opposing-counsel",
  adjustersOnFilesExport: "api/v2/export/export-adjusters-on-files",
  policeStationsMeta: "api/v2/export/list-of-police-stations",
  policeStationsExport: "api/v2/export/export-list-of-police-stations",
  vsrMeta: "api/v2/export/vsr",
  vsrExport: "api/v2/export/export-vsr",
  accounts: "api/v2/email/accounts",
  defaultAccount: "api/v2/email/default",
  deleteEmail: "api/v2/email/delete",
  moveEmail: "api/v2/email/move",
  trashEmail: "api/v2/email/trash",
  starredEmail: "api/v2/emails/starred",
  starEmail: "api/v2/email",
  trashList: "api/v2/email/folder/trash",
  threadView: "api/v2/email/thread",
  unlinkAccount: "api/v2/email/accounts",
  showEmail: "api/v2/email/show",
  unlinkAttachment: "api/v2/email/unlink",
  //Notification
  getNotification: "api/v2/notifications",
  readNotificationById: "api/v2/notifications/read",
  readMultipleNotification: "api/v2/notifications/read-multiple",
  readAllNotification: "api/v2/notifications/read-all",
  deleteNotificationById: "api/v2/notifications/clear",
  deleteAllNotification: "api/v2/notifications/clear-all",
  unreadNotification: "api/v2/notifications/unread-count",
  notificationResponse: "api/v2/notification-response",
  createLabel: "api/v2/labels/create",
  renameLabel: "api/v2/labels/rename",
  deleteLabel: "api/v2/labels/delete",
  labelsList: "api/v2/labels/list",
  labelEmails: "api/v2/labels/emails",
  linkEmailToLabel: "api/v2/labels/link-email",
  unlinkEmailFromLabel: "api/v2/labels/unlink-email",
  listUser: "api/v2/setup/users/list",
  addUser: "api/v2/setup/users/store",
  showUser: "api/v2/setup/users/show",
  updateUser: "api/v2/setup/users/update",
  userMeta: "api/v2/setup/users/meta",
  deleteUser: "api/v2/setup/users/delete",
  firmMeta: "api/v2/setup/firm-meta",
  showFirm: "api/v2/setup/firm-update",
  updateFirm: "api/v2/setup/firm-update",
  // Master endpoints
  masterList: "api/v2/setup/master/list",
  createMaster: "api/v2/setup/master/store",
  updateMaster: "api/v2/setup/master/update",
  updateMasterStatus: "api/v2/setup/master/updateStatus",
  deleteMaster: "api/v2/setup/master/delete",
  showMaster: "api/v2/setup/master/show",
  // Roles endpoints
  rolesList: "api/v2/setup/roles/list",
  permissionsList: "api/v2/setup/roles/permissions",
  showRole: "api/v2/setup/roles/show",
  createRole: "api/v2/setup/roles/store",
  updateRole: "api/v2/setup/roles/update",
  deleteRole: "api/v2/setup/roles/delete",

  // Accounting
  accountList: "api/v2/file/accounting/expence/list",
  singleCost: "api/v2/file/accounting/expence/show",
  deleteCost: "api/v2/file/accounting/expence/delete",
  addCost: "api/v2/file/accounting/expence/save",
  updateCost: "api/v2/file/accounting/expence/update",
  accountingMeta: "api/v2/file/accounting/expence/meta",

  // Bank Transactions (Deposits)
  depositList: "api/v2/file/accounting/deposit/list",
  depositSave: "api/v2/file/accounting/deposit/save",
  depositUpdate: "api/v2/file/accounting/deposit/update",
  depositDelete: "api/v2/file/accounting/deposit/delete",
  depositShow: "api/v2/file/accounting/deposit/show",
  accidentBenifitMeta: "api/v2/file/accident-benefits/meta",

  // Third Party Invoice
  thirdPartyInvoiceList: "api/v2/file/accounting/third-party-invoices/list",
  addThirdPartyInvoice: "api/v2/file/accounting/third-party-invoices/save",
  updateThirdPartyInvoice: "api/v2/file/accounting/third-party-invoices/update",
  deleteThirdPartyInvoice: "api/v2/file/accounting/third-party-invoices/delete",
  thirdPartyInvoiceShow: "api/v2/file/accounting/third-party-invoices/show",
  unlinkThirdPartyInvoice: "api/v2/file/accounting/pay-bills/unlink",
  payBillsList: "api/v2/file/accounting/pay-bills/list",
  payBills: "api/v2/file/accounting/pay-bills/pay",

  // Invoice
  invoiceList: "api/v2/file/accounting/invoice/list",
  invoiceShow: "api/v2/file/accounting/invoice/show",
  invoiceUnbilledList: "api/v2/file/accounting/invoice/unbilled-list",
  invoiceCreate: "api/v2/file/accounting/invoice/create-invoice",
  invoiceUpdate: "api/v2/file/accounting/invoice/update-invoice",
  invoiceDelete: "api/v2/file/accounting/invoice/delete",
  invoicePaymentDetail: "api/v2/file/accounting/invoice-payments/invoice-detail",
  invoicePaymentSaveTrust: "api/v2/file/accounting/invoice-payments/save/trust-bank",
  invoicePaymentSaveOperating: "api/v2/file/accounting/invoice-payments/save/operating-bank",
  invoicePaymentHistory: "api/v2/file/accounting/invoice-payments/invoice",
  invoicePaymentDelete: "api/v2/file/accounting/invoice-payments/delete",
  invoiceWriteOff: "api/v2/file/accounting/invoice-write-off/save",

  // Final Settlement
  finalSettlementShow: "api/v2/file/accounting/final-settlement/show",
  finalSettlementSave: "api/v2/file/accounting/final-settlement/save",
  downloadFinalSettlement: "api/v2/file/accounting/final-settlement/download",

};

