export const endpoints = {
  login: "api/login",
  signup: "api/firm/register",
  signupMeta: "api/form-data",
  forgotpassword: "api/forgot-password",
  resetpassword: "/api/reset-password",
  dashboard: "api/v2/dashboard",
  uploadAttachment: "api/v2/attachment",
  workstation_list: "api/v2/file/workstation",
  matterMeta: "api/v2/file/initial/meta",
  createMatter: "api/v2/file/initial/save",
  matter: "api/v2/file/initial/show",
  applicantMeta: "api/v2/file/applicant-information/meta",
  createApplicantInfo: "api/v2/file/applicant-information",
  applicantInfo: "api/v2/file/applicant-information/show",
  createIdentification: "api/v2/file/identification",
  identificationMeta: "api/v2/file/identification/meta",
  identification: "api/v2/file/identification/show",
  createEmployment: "api/v2/file/employement",
  employmentMeta: "api/v2/file/employement/meta",
  employment: "api/v2/file/employement/show",
  schoolCaregiver: "api/v2/file/school-or-caregiver/show",
  createSchoolCaregiver: "api/v2/file/school-or-caregiver",
  schoolCaregiverMeta: "api/v2/file/school-or-caregiver/meta",
  representativeReferral: "api/v2/file/representative-referral/show",
  createRepresentativeReferral: "api/v2/file/representative-referral",
  representativeReferralMeta: "api/v2/file/representative-referral/meta",
  createPrimaryEhc: "api/v2/file/primary-ehc",
  primaryEhcmeta: "api/v2/file/primary-ehc/meta",
  primaryEhc: "api/v2/file/primary-ehc/show",
  createSecondaryEhc: "api/v2/file/secondary-ehc",
  secondaryEhcMeta: "api/v2/file/secondary-ehc/meta",
  secondaryEhc: "api/v2/file/secondary-ehc/show",
  createAccidentInfo: "api/v2/file/accident-detail",
  accidentInfoMeta: "api/v2/file/accident-detail/meta",
  accidentInfo: "api/v2/file/accident-detail/show",
  createInsurance: "api/v2/file/accident-benefits/insurance",
  insurance: "api/v2/file/accident-benefits/insurance/show",
  metaAccidentBenefits: "api/v2/file/accident-benefits/meta",
  adjuster: "api/v2/file/accident-benefits/adjuster/show",
  createAdjuster: "api/v2/file/accident-benefits/adjuster",
  deleteAdjuster: "api/v2/file/accident-benefits/adjuster/delete",
  vechile: "api/v2/file/accident-benefits/vehicle/show",
  createVechile: "api/v2/file/accident-benefits/vehicle",
  deleteVechile: "api/v2/file/accident-benefits/adjuster/delete",
  sectionList: "api/v2/file/accident-benefits/section-33/list",
  section: "api/v2/file/accident-benefits/section-33/show",
  createSection: "api/v2/file/accident-benefits/section-33",
  updateSection: "api/v2/file/accident-benefits/section-33",
  deleteSectionList: "api/v2/file/accident-benefits/section-33/delete",
  deleteSectionCommunication:
    "api/v2/file/accident-benefits/section-33/delete-communication",
  deleteSectiondocument:
    "api/v2/file/accident-benefits/section-33/delete-document",
  latList: "api/v2/file/accident-benefits/lat/list",
  deleteLat: "api/v2/file/accident-benefits/lat",
  lat: "api/v2/file/accident-benefits/lat/show",
  createLat: "api/v2/file/accident-benefits/lat",
  updateLat: "api/v2/file/accident-benefits/lat",
  createAbCounsel: "api/v2/file/accident-benefits/ab-counsel",
  abCounsel: "api/v2/file/accident-benefits/ab-counsel/show",
  createTpInsurance: "api/v2/file/third-party/insurance",
  tpInsurance: "api/v2/file/third-party/insurance/show",
  deleteTpInsurance: "api/v2/file/third-party/insurance/delete",
  createTpAdjuster: "api/v2/file/third-party/adjuster",
  tpAdjuster: "api/v2/file/third-party/adjuster/show",
  deleteTpAdjuster: "api/v2/file/third-party/adjuster/delete",
  driverInfo: "api/v2/file/third-party/driver-information/show",
  createDriverInfo: "api/v2/file/third-party/driver-information",
  createOwnerInfo: "api/v2/file/third-party/owner-information",
  ownerInfo: "api/v2/file/third-party/owner-information/show",
  deleteOwnerInfo: "api/v2/file/third-party/owner-information/delete",
  deleteOwnerDirector:
    "api/v2/file/third-party/owner-information/director-delete",
  createTpVechile: "api/v2/file/third-party/vehicle",
  tpVechile: "api/v2/file/third-party/vehicle/show",
  section258List: "api/v2/file/third-party/section-258/list",
  createSection258: "api/v2/file/third-party/section-258",
  section258: "api/v2/file/third-party/section-258/show",
  updateSection258: "api/v2/file/third-party/section-258",
  deleteSection258Communication:
    "api/v2/file/third-party/section-258/delete-communication",
  deleteSection258document:
    "api/v2/file/third-party/section-258/delete-document",
  deleteSection258List: "api/v2/file/third-party/section-258/delete",
  createTpCounsel: "api/v2/file/third-party/tp-counsel",
  tpCounsel: "api/v2/file/third-party/tp-counsel/show",
  soc: "api/v2/file/soc/show",
  createSoc: "api/v2/file/soc",
  createStatement: "api/v2/file/soc/statamnet-of-defence",
  statement: "api/v2/file/soc/statamnet-of-defence/show",
  createScheduled: "api/v2/file/discovery/scheduled",
  scheduled: "api/v2/file/discovery/scheduled/show",
  createAod: "api/v2/file/discovery/aod",
  aod: "api/v2/file/discovery/aod/show",
  createUndertaking: "api/v2/file/discovery/undertaking",
  undertaking: "api/v2/file/discovery/undertaking/show",
  conflictList: "api/v2/file/document/list/conflict-search",
  createConflict: "api/v2/file/document/save/conflict-search",
  deleteConflict: "api/v2/file/document/delete",
  updateConflict: "api/v2/file/document",
  createClient: "api/v2/file/document/save/client-documents",
  clientList: "api/v2/file/document/list/client-documents",
  updateClient: "api/v2/file/document",
  deleteClient: "api/v2/file/document/delete",
  createInsuranceDoc: "api/v2/file/document/save/insurance-ownership",
  insuranceDocList: "api/v2/file/document/list/insurance-ownership",
  deleteInsuranceDoc: "api/v2/file/document/delete",
  updateInsuranceDoc: "api/v2/file/document",
  createPolice: "api/v2/file/document/save/police-report",
  updatePolice: "api/v2/file/document",
  policeList: "api/v2/file/document/list/police-report",
  deletePolice: "api/v2/file/document/delete",
  createMedical: "api/v2/file/document/save/medical-reports",
  updateMedical: "api/v2/file/document",
  medicalList: "api/v2/file/document/list/medical-reports",
  deleteMedical: "api/v2/file/document/delete",
  createAccounting: "api/v2/file/document/save/accounting",
  updateAccounting: "api/v2/file/document",
  accountinglist: "api/v2/file/document/list/accounting",
  deleteAccounting: "api/v2/file/document/delete",
  createClientCorrespondence: "api/v2/file/correspondence/save/client",
  clientCorrespondenceList: "api/v2/file/correspondence/list/client",
  updateClientCorrespondence: "api/v2/file/correspondence",
  deleteClientCorrespondence: "api/v2/file/correspondence/delete",
  createInsuranceExamination: "api/v2/file/insurance-examination",
  updateInsuranceExamnation: "api/v2/file/insurance-examination",
  insuranceExamination: "api/v2/file/insurance-examination/show",
  deleteInsuranceExamination: "api/v2/file/insurance-examination/delete",
  insuranceExaminationList: "api/v2/file/insurance-examination/list",
  createVsrInsuranceExamination: "api/v2/file/vsr-examination",
  updateVsrInsuranceExamnation: "api/v2/file/vsr-examination",
  vsrInsuranceExamination: "api/v2/file/vsr-examination/show",
  deleteVsrInsuranceExamination: "api/v2/file/vsr-examination/delete",
  vsrInsuranceExaminationList: "api/v2/file/vsr-examination/list",
  createOcf: "api/v2/file/tracking/production/ocf-productions",
  ocf: "api/v2/file/tracking/production/ocf-productions/show",
  createOcf1: "api/v2/file/tracking/production/ocf-1",
  ocf1: "api/v2/file/tracking/production/ocf-1/show",
  createOcf2: "api/v2/file/tracking/production/ocf-2",
  ocf2: "api/v2/file/tracking/production/ocf-2/show",
  createOcf3: "api/v2/file/tracking/production/ocf-3",
  ocf3: "api/v2/file/tracking/production/ocf-3/show",
  createOcf5: "api/v2/file/tracking/production/ocf-5",
  ocf5: "api/v2/file/tracking/production/ocf-5/show",
  createOcf6: "api/v2/file/tracking/production/ocf-6",
  ocf6: "api/v2/file/tracking/production/ocf-6/show",
  createOcf10: "api/v2/file/tracking/production/ocf-10",
  ocf10: "api/v2/file/tracking/production/ocf-10/show",
  createOhif: "api/v2/file/tracking/production/ohip-decorded-summary",
  ohif: "api/v2/file/tracking/production/ohip-decorded-summary/show",
  deleteOhif: "api/v2/file/tracking/production/ohip-decorded-summary/delete",
  createPoliceReport: "api/v2/file/tracking/production/police-report",
  policeReport: "api/v2/file/tracking/production/police-report/show",
  deletePoliceReport: "api/v2/file/tracking/production/police-report/delete",
  createHospitalReport: "api/v2/file/tracking/production/hospital-report",
  hospitalReport: "api/v2/file/tracking/production/hospital-report/show",
  deleteHospitalReport:
    "api/v2/file/tracking/production/hospital-report/delete",
  createAmbulanceReport: "api/v2/file/tracking/production/ambulance-report",
  ambulanceReport: "api/v2/file/tracking/production/ambulance-report/show",
  deleteAmbulanceReport:
    "api/v2/file/tracking/production/ambulance-report/delete",
  createFamilyDoctor: "api/v2/file/tracking/production/family-doctor-cnr",
  familyDoctor: "api/v2/file/tracking/production/family-doctor-cnr/show",
  deleteFamilyDoctor:
    "api/v2/file/tracking/production/family-doctor-cnr/delete",
  createPharmacy:
    "api/v2/file/tracking/production/pharmacy-prescription-summary",
  pharmacy:
    "api/v2/file/tracking/production/pharmacy-prescription-summary/show",
  deletePharmacy:
    "api/v2/file/tracking/production/pharmacy-prescription-summary/delete",
  createPhysiotherapy: "api/v2/file/tracking/production/physiotherapy-cnr",
  physiotherapy: "api/v2/file/tracking/production/physiotherapy-cnr/show",
  deletePhysiotherapy:
    "api/v2/file/tracking/production/physiotherapy-cnr/delete",
  createWalk: "api/v2/file/tracking/production/walk-in-clinic-cnr",
  walk: "api/v2/file/tracking/production/walk-in-clinic-cnr/show",
  deleteWalk: "api/v2/file/tracking/production/walk-in-clinic-cnr/delete",
  createStatutory: "api/v2/file/tracking/statutory-declaration",
  statutory: "api/v2/file/tracking/statutory-declaration/show",
  createTax: "api/v2/file/tracking/tax-returns",
  tax: "api/v2/file/tracking/tax-returns/show",
  createBank: "api/v2/file/tracking/bank-statements",
  bank: "/api/v2/file/tracking/bank-statements/show",
  createSue: "api/v2/file/tracking/sue-to-driver-owner",
  sue: "api/v2/file/tracking/sue-to-driver-owner/show",
  deleteSue: "api/v2/file/tracking/sue-to-driver-owner/delete",
  createNonEngagement: "api/v2/file/tracking/non-engagement",
  deleteNonEngagement: "api/v2/file/tracking/sue-to-driver-owner/delete",
  nonEngagement: "api/v2/file/tracking/non-engagement/show",
  CreateClientSettlement: "api/v2/file/client-memo-settlement",
  clientSettlement: "api/v2/file/client-memo-settlement/show",
  createCost: "api/v2/file/accounting/expence",
  createTask: " api/v2/file/task",
  updateTask: " api/v2/file/task",
};
